// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {uuid} from '../models';

export function CreateEvent(arg1:models.Event):Promise<models.Event>;

export function CreateFollowspot(arg1:models.FollowspotCue):Promise<models.FollowspotCue>;

export function CreateFollowspotCue(arg1:models.FollowspotCue):Promise<models.FollowspotCue>;

export function CreateUser(arg1:models.User):Promise<models.User>;

export function DeleteEvent(arg1:models.Event):Promise<models.Event>;

export function DeleteFollowspot(arg1:models.FollowspotCue):Promise<models.FollowspotCue>;

export function DeleteFollowspotCue(arg1:models.FollowspotCue):Promise<models.FollowspotCue>;

export function DeleteUser(arg1:models.User):Promise<models.User>;

export function GetEventById(arg1:uuid.UUID):Promise<models.Event>;

export function GetEvents():Promise<Array<models.Event>>;

export function GetFollowspotById(arg1:uuid.UUID):Promise<models.FollowspotCue>;

export function GetFollowspotCueById(arg1:uuid.UUID):Promise<models.FollowspotCue>;

export function GetFollowspotCues(arg1:uuid.UUID):Promise<Array<models.FollowspotCue>>;

export function GetFollowspots(arg1:uuid.UUID):Promise<Array<models.FollowspotCue>>;

export function GetUserById(arg1:uuid.UUID):Promise<models.User>;

export function GetUsers():Promise<Array<models.User>>;

export function SQLStart(arg1:string):Promise<void>;

export function UpdateEvent(arg1:models.Event):Promise<models.Event>;

export function UpdateFollowspot(arg1:models.FollowspotCue):Promise<models.FollowspotCue>;

export function UpdateFollowspotCue(arg1:models.FollowspotCue):Promise<models.FollowspotCue>;

export function UpdateUser(arg1:models.User):Promise<models.User>;
