// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateEvent(arg1) {
  return window['go']['controllers']['App']['CreateEvent'](arg1);
}

export function CreateFollowspot(arg1) {
  return window['go']['controllers']['App']['CreateFollowspot'](arg1);
}

export function CreateFollowspotCue(arg1) {
  return window['go']['controllers']['App']['CreateFollowspotCue'](arg1);
}

export function CreateUser(arg1) {
  return window['go']['controllers']['App']['CreateUser'](arg1);
}

export function DeleteEvent(arg1) {
  return window['go']['controllers']['App']['DeleteEvent'](arg1);
}

export function DeleteFollowspot(arg1) {
  return window['go']['controllers']['App']['DeleteFollowspot'](arg1);
}

export function DeleteFollowspotCue(arg1) {
  return window['go']['controllers']['App']['DeleteFollowspotCue'](arg1);
}

export function DeleteUser(arg1) {
  return window['go']['controllers']['App']['DeleteUser'](arg1);
}

export function GetEventById(arg1) {
  return window['go']['controllers']['App']['GetEventById'](arg1);
}

export function GetEvents() {
  return window['go']['controllers']['App']['GetEvents']();
}

export function GetFollowspotById(arg1) {
  return window['go']['controllers']['App']['GetFollowspotById'](arg1);
}

export function GetFollowspotCueById(arg1) {
  return window['go']['controllers']['App']['GetFollowspotCueById'](arg1);
}

export function GetFollowspotCues(arg1) {
  return window['go']['controllers']['App']['GetFollowspotCues'](arg1);
}

export function GetFollowspots(arg1) {
  return window['go']['controllers']['App']['GetFollowspots'](arg1);
}

export function GetUserById(arg1) {
  return window['go']['controllers']['App']['GetUserById'](arg1);
}

export function GetUsers() {
  return window['go']['controllers']['App']['GetUsers']();
}

export function SQLStart(arg1) {
  return window['go']['controllers']['App']['SQLStart'](arg1);
}

export function SelectEvent(arg1) {
  return window['go']['controllers']['App']['SelectEvent'](arg1);
}

export function UpdateEvent(arg1) {
  return window['go']['controllers']['App']['UpdateEvent'](arg1);
}

export function UpdateFollowspot(arg1) {
  return window['go']['controllers']['App']['UpdateFollowspot'](arg1);
}

export function UpdateFollowspotCue(arg1) {
  return window['go']['controllers']['App']['UpdateFollowspotCue'](arg1);
}

export function UpdateUser(arg1) {
  return window['go']['controllers']['App']['UpdateUser'](arg1);
}
