// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function Migration() {
  return window['go']['main']['App']['Migration']();
}

export function SurrealSignin(arg1, arg2) {
  return window['go']['main']['App']['SurrealSignin'](arg1, arg2);
}
